var plugin = requirePlugin("myPlugin")
Page({
  data:{
    qnConf:{
      accessKey:'uva-aaonM8dukeR6phc9yuPBrOXk9brrNW_PxLD7',
      secretKey:'oZMMVN6phk49lG0J1xwmi1Ju0ETT15EnAEWcU9Cs',
      bucket:'colorcun-attr',
      fileType:'image',
      region:'华东'
    },
    upConf:{
      prefixPath:'prefixPath',
      count:3,
    },
    files:[
      {
        path:'https://qn.colorcun.com/prefixPath/2019-06-28/443695.png',
        progress:50,
        current:0,
      }
    ],
    hasAddFile:true,
  },
  onLoad: function() {
    plugin.getOpenid().then(res=>{
      console.log(res);
    })
    plugin.getTokenQiniu({
      accessKey:'uva-aaonM8dukeR6phc9yuPBrOXk9brrNW_PxLD7',
      secretKey:'oZMMVN6phk49lG0J1xwmi1Ju0ETT15EnAEWcU9Cs',
      bucket:'colorcun-attr',
      fileType:'image',
    }).then(res=>{
      console.log(res);
    })
  },
  qnevent(e){
    console.log('qnevent',e.detail);
    this.setData({
      files:e.detail.data,
      hasAddFile:e.detail.data.length<this.data.upConf.count
    })
  }
})