var plugin = requirePlugin("myPlugin")
Page({
  data:{
    qnConf:{
      accessKey:'p7WjLuVs1GTpFRH_7mnZ0KidZfWXNh5_nW_2X_eJ',
      secretKey:'mWb6EV70xL2opJU1uwWk9Z7MyAUjPF8cLVwvd9x6',
      bucket:'fotoo',
      fileType:'image',
      region:'华东',
      domain:'http://qn001.pfotoo.com'
    },
    upConf:{
      prefixPath:'mkblk',
      count:3,
    },
    files:[],
    hasAddFile:true,//出现上传加号
    token:'',//七牛token

    upConf2:{
      prefixPath:'prefixPath',
      count:3,
      group:'222',
      loading:'ring',
    },
    files2:[],
    hasAddFile2:true,//出现上传加号

    hasHidden:true,//图片预览
    currentIndex:0,

    fsm:wx.getFileSystemManager(),
    hasIphone:false,
  },
  onLoad: function() {
    console.log(plugin)
    plugin.getOpenid().then(res=>{
      console.log(res);
    })
    plugin.getTokenQiniu({
      accessKey:'p7WjLuVs1GTpFRH_7mnZ0KidZfWXNh5_nW_2X_eJ',
      secretKey:'mWb6EV70xL2opJU1uwWk9Z7MyAUjPF8cLVwvd9x6',
      bucket:'fotoo',
      fileType:'image',
    }).then(res=>{
      console.log(res);
      this.setData({
        token:res,
      })
    })
    //this.previewImage()
    let sys=wx.getSystemInfoSync();
    this.setData({
      hasIphone:sys.system.toLowerCase().indexOf('ios')>-1,
    })
  },
  qnevent(e){
    console.log('qnevent',e.detail);
    this.setData({
      files:e.detail.data,
      hasAddFile:e.detail.data.length<this.data.upConf.count
    })
  },
  qnevent2(e){
    console.log('qnevent2',e.detail);
    this.setData({
      files2:e.detail.data,
      hasAddFile2:e.detail.data.length<this.data.upConf2.count
    })
  },
  previewImage(){
    let p1='https://qn001.pfotoo.com/oxcc/md147418.jpg.lim.jpg?x='+Math.random()
    this.setData({
      urls:[
        p1,
        'https://qn001.pfotoo.com/mkblk/md441234.jpg.lim.jpg?x='+Math.random(),
      ],
      current:p1,
      hasHidden:false,
    })
  },
  previewEvent(e){
    console.log('previewEvent(e)',e)
    this.setData({
      currentIndex:e.detail.data.current
    })
  },
  previewHide(){
    this.setData({
      currentIndex:0,
      hasHidden:true,
    })
  },
})