var plugin = requirePlugin("myPlugin")
Page({
  data:{
    qnConf:{
      accessKey:'p7WjLuVs1GTpFRH_7mnZ0KidZfWXNh5_nW_2X_eJ',
      secretKey:'mWb6EV70xL2opJU1uwWk9Z7MyAUjPF8cLVwvd9x6',
      bucket:'fotoo',
      fileType:'image',
      region:'华东',
      domain:'http://qn001.pfotoo.com'
    },
    upConf:{
      prefixPath:'prefixPath',
      count:3,
    },
    files:[
      {
        path:'https://qn.colorcun.com/prefixPath/2019-06-28/443695.png',
        progress:50,
        current:0,
      }
    ],
    hasAddFile:true,//出现上传加号
    token:'',//七牛token

    upConf2:{
      prefixPath:'prefixPath',
      count:3,
      group:'222',
      loading:'ring',
    },
    files2:[
      {
        path:'https://qn.colorcun.com/prefixPath/2019-06-28/443695.png',
        progress:50,
        current:0,
      }
    ],
    hasAddFile2:true,//出现上传加号
  },
  onLoad: function() {
    console.log(plugin)
    plugin.getOpenid().then(res=>{
      console.log(res);
    })
    plugin.getTokenQiniu({
      accessKey:'p7WjLuVs1GTpFRH_7mnZ0KidZfWXNh5_nW_2X_eJ',
      secretKey:'mWb6EV70xL2opJU1uwWk9Z7MyAUjPF8cLVwvd9x6',
      bucket:'fotoo',
      fileType:'image',
    }).then(res=>{
      console.log(res);
      this.setData({
        token:res,
      })
    })
  },
  qnevent(e){
    console.log('qnevent',e.detail);
    this.setData({
      files:e.detail.data,
      hasAddFile:e.detail.data.length<this.data.upConf.count
    })
  },
  qnevent2(e){
    console.log('qnevent2',e.detail);
    this.setData({
      files2:e.detail.data,
      hasAddFile2:e.detail.data.length<this.data.upConf2.count
    })
  }
})